# Generated by Django 2.2.9 on 2020-01-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0004_auto_20200124_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pcgame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('winner', models.BooleanField(blank=True, null=True)),
                ('computer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_choice', to='games.Weapon')),
                ('human_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_choice', to='games.Weapon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
