# Generated by Django 2.2.9 on 2020-01-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200116_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='defender_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='human_choice', to='games.Weapon'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.IntegerField(choices=[(0, '가위'), (1, '바위'), (2, '보')]),
        ),
    ]
