# Generated by Django 2.2.9 on 2020-01-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200116_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='attacker_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attacker_choice', to='games.Weapon'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='defender_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defender_choice', to='games.Weapon'),
        ),
    ]
